# Use the official lightweight Nginx image
FROM nginx:alpine

# Copy all frontend files to the Nginx public folder
COPY . /usr/share/nginx/html

# Expose port 80 (Internal Nginx port)
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]